plugins {
    id 'com.android.library'
}

android {
    namespace 'ru.mirea.fedorov.dogguide.data'
    compileSdk 36

    defaultConfig {
        minSdk 24
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    androidResources {
        noCompress 'tflite'
    }
}

dependencies {
    implementation project(':domain')
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.room:room-runtime:2.6.1'
    annotationProcessor 'androidx.room:room-compiler:2.6.1'
    implementation 'org.tensorflow:tensorflow-lite-task-vision:0.4.4'
    implementation platform('com.google.firebase:firebase-bom:33.7.0')
    implementation 'com.google.firebase:firebase-auth'
}
